--- #YAML:1.0
name:               Music-Tag-MP3
version:            0.32
abstract:           Plugin module for Music::Tag to get information from id3 tags
author:
    - Edward Allen (ealleniii _at_ cpan _dot_ org)
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Data::Dumper:  2
    Encode:        2.12
    File::Copy:    0
    File::Spec:    3.24
    IO::File:      1.13
    MP3::Info:     1.23
    MP3::Tag:      0.9701
    Music::Tag:    0.27
    Test::More:    0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
